# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

if CarrierBranch.count == 0
  CarrierBranch.create!([
    { :carrier_id => 1, :name => "Farmers", :sequence => 1, :is_default => true, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-26 13:53:03", :last_employee_id => 0 },
    { :carrier_id => 2, :name => "USAA", :sequence => 1, :is_default => true, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-26 13:53:03", :last_employee_id => 0 },
    { :carrier_id => 3, :name => "MetLife", :sequence => 1, :is_default => true, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-26 13:53:03", :last_employee_id => 0 },
    { :carrier_id => 4, :name => "Fidelity", :sequence => 1, :is_default => true, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-26 13:53:03", :last_employee_id => 0 },
    { :carrier_id => 5, :name => "Chubb", :sequence => 1, :is_default => true, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-26 13:53:03", :last_employee_id => 0 }
  ])
end

if Employee.count == 0
Employee.create!([
  { :first_name => "Benjamin", :last_name => "Hall", :role_id => 0, :email => "benjamin@hall.com", :password => "test12345", :is_login => false,  :telephone_office => "", :telephone_mobile => "", :is_assign_repair => false, :tasks_daily_max => 0, :tasks_daily_overflow => 0, :started => nil, :credential_id => 0, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-19 17:16:13", :last_employee_id => 0 },
  { :first_name => "Bryan", :last_name => "Quasthoff", :role_id => 0, :email => "bryan@quasthoff.com", :password => "test12345", :is_login => false,  :telephone_office => "", :telephone_mobile => "", :is_assign_repair => false, :tasks_daily_max => 0, :tasks_daily_overflow => 0, :started => nil, :credential_id => 0, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-19 17:16:13", :last_employee_id => 0 },
  { :first_name => "Edgar", :last_name => "De La Cruz", :role_id => 0, :email => "edgar@dalacruz.com", :password => "test12345", :is_login => false, :telephone_office => "", :telephone_mobile => "", :is_assign_repair => false, :tasks_daily_max => 0, :tasks_daily_overflow => 0, :started => nil, :credential_id => 0, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-19 17:16:56", :last_employee_id => 0 },
  { :first_name => "Steve", :last_name => "Hawes", :role_id => 0, :email => "steve@hawes.com", :password => "test12345", :is_login => false, :telephone_office => "", :telephone_mobile => "", :is_assign_repair => false, :tasks_daily_max => 0, :tasks_daily_overflow => 0, :started => nil, :credential_id => 0, :active => true, :created => nil, :created_employee_id => 0, :timestamp => "2013-10-19 17:16:56", :last_employee_id => 0 }
])
end

if ClaimAuditQuestion.count == 0
  ClaimAuditQuestion.create!([
    { :category => "Admin", :question => "Professionally Written", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:42", :updated_at => "2013-10-30 07:41:42" },
    { :category => "Admin", :question => "Vehicle Admin Complete", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:42", :updated_at => "2013-10-30 07:41:42" },
    { :category => "Admin", :question => "Estimate Admin Complete", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:42", :updated_at => "2013-10-30 07:41:42" },
    { :category => "Compliance", :question => "Parts Guidelines", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Compliance", :question => "State Guidelines", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Compliance", :question => "Carrer Guidelines", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Estimation Decisions", :question => "Tax Rate Correct", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Estimation Decisions", :question => "Correct Tax Structure", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Estimation Decisions", :question => "Labour Rate Supported", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Estimation Decisions", :question => "Repair Decision Accurate", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Estimation Decisions", :question => "Labour Hours Accurate", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" },
    { :category => "Estimation Decisions", :question => "APU Accurate", :response => nil, :min_exception => nil, :max_exception => nil, :created_at => "2013-10-30 07:41:43", :updated_at => "2013-10-30 07:41:43" }
  ])
end


if ClaimAwaitingAudit.count == 0
ClaimAwaitingAudit.create!([
  { :claim_number => "123456708", :claim_type => "IV", :carrier_branch_id => 1, :employee_id => 1, :severity => 1234.34, :duration_net => 19.4, :estimate_date => "2013-06-06", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456718", :claim_type => "CV", :carrier_branch_id => 2, :employee_id => 2, :severity => 1934.13, :duration_net => 23.2, :estimate_date => "2013-06-06", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456728", :claim_type => "IV", :carrier_branch_id => 3, :employee_id => 2, :severity => 1123.87, :duration_net => 21.1, :estimate_date => "2013-06-06", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456738", :claim_type => "IV", :carrier_branch_id => 4, :employee_id => 1, :severity => 537.45, :duration_net => 24.1, :estimate_date => "2013-06-06", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456748", :claim_type => "CV", :carrier_branch_id => 5, :employee_id => 1, :severity => 2103.45, :duration_net => 16.5, :estimate_date => "2013-06-06", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456758", :claim_type => "CV", :carrier_branch_id => 1, :employee_id => 4, :severity => 674.43, :duration_net => 21.3, :estimate_date => "2013-06-07", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456768", :claim_type => "IV", :carrier_branch_id => 2, :employee_id => 3, :severity => 1675.54, :duration_net => 22.6, :estimate_date => "2013-06-08", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456778", :claim_type => "CV", :carrier_branch_id => 3, :employee_id => 2, :severity => 2056.76, :duration_net => 23.6, :estimate_date => "2013-06-09", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456788", :claim_type => "IV", :carrier_branch_id => 1, :employee_id => 2, :severity => 1756.34, :duration_net => 19.4, :estimate_date => "2013-06-09", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456798", :claim_type => "IV", :carrier_branch_id => 2, :employee_id => 4, :severity => 865.39, :duration_net => 17.4, :estimate_date => "2013-06-09", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456709", :claim_type => "CV", :carrier_branch_id => 4, :employee_id => 1, :severity => 776.54, :duration_net => 18.7, :estimate_date => "2013-06-09", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456719", :claim_type => "CV", :carrier_branch_id => 4, :employee_id => 2, :severity => 2341.45, :duration_net => 25.2, :estimate_date => "2013-06-09", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456729", :claim_type => "IV", :carrier_branch_id => 5, :employee_id => 3, :severity => 1454.43, :duration_net => 20.8, :estimate_date => "2013-06-09", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456739", :claim_type => "CV", :carrier_branch_id => 4, :employee_id => 3, :severity => 687.98, :duration_net => 16.3, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456749", :claim_type => "IV", :carrier_branch_id => 5, :employee_id => 1, :severity => 1154.41, :duration_net => 21.3, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456759", :claim_type => "IV", :carrier_branch_id => 2, :employee_id => 2, :severity => 968.54, :duration_net => 19.5, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456769", :claim_type => "CV", :carrier_branch_id => 3, :employee_id => 3, :severity => 2754.34, :duration_net => 24.7, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456779", :claim_type => "CV", :carrier_branch_id => 4, :employee_id => 3, :severity => 1651.37, :duration_net => 23.4, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456789", :claim_type => "IV", :carrier_branch_id => 1, :employee_id => 3, :severity => 997.56, :duration_net => 19.4, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456799", :claim_type => "IV", :carrier_branch_id => 2, :employee_id => 2, :severity => 1021.32, :duration_net => 20.6, :estimate_date => "2013-06-10", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456750", :claim_type => "IV", :carrier_branch_id => 4, :employee_id => 2, :severity => 1084.36, :duration_net => 19.6, :estimate_date => "2013-06-11", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456760", :claim_type => "CV", :carrier_branch_id => 4, :employee_id => 2, :severity => 2845.35, :duration_net => 23.5, :estimate_date => "2013-06-11", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456770", :claim_type => "CV", :carrier_branch_id => 3, :employee_id => 1, :severity => 1561.75, :duration_net => 21.6, :estimate_date => "2013-06-11", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456780", :claim_type => "IV", :carrier_branch_id => 4, :employee_id => 1, :severity => 897.68, :duration_net => 18.9, :estimate_date => "2013-06-11", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" },
  { :claim_number => "123456790", :claim_type => "IV", :carrier_branch_id => 1, :employee_id => 2, :severity => 1022.52, :duration_net => 20.4, :estimate_date => "2013-06-11", :active => true, :created => "2013-10-19 17:21:51", :created_employee_id => 0, :completed => nil, :completed_employee_id => 0, :timestamp => "2013-10-20 00:23:22" }
])
end


if ConstantEstimatingSystem.count == 0
ConstantEstimatingSystem.create!([
  { :name => "CCC One", :active => true },
  { :name => "Mitchell", :active => true },
  { :name => "Audatex", :active => true }
])

end

if ConstantResponse.count == 0
ConstantResponse.create!([
  { :response_type_id => 29, :name => "YES", :sequence => 1, :active => true },
  { :response_type_id => 29, :name => "NO", :sequence => 2, :active => true },
  { :response_type_id => 29, :name => "N/A", :sequence => 3, :active => true }
])
end


if ConstantType.count == 0
ConstantType.create!([
  { :type => "status", :name => "Claim", :active => true },
  { :type => "status", :name => "Task", :active => true },
  { :type => "reason", :name => "Disqualify", :active => true },
  { :type => "reason", :name => "Unable to Complete", :active => true },
  { :type => "duration", :name => "Due Within", :active => true },
  { :type => "mail_send", :name => "Invoice", :active => true },
  { :type => "mail_send", :name => "Disqualify", :active => true },
  { :type => "mail_send", :name => "Cancel Estimate", :active => true },
  { :type => "mail_send", :name => "Check on Request", :active => true },
  { :type => "mail_send", :name => "Repair Shop Selected", :active => true },
  { :type => "mail_receive", :name => "Claim Assignment", :active => true },
  { :type => "mail_receive", :name => "Photos", :active => true },
  { :type => "limit", :name => "amount", :active => true },
  { :type => "limit", :name => "percent", :active => true },
  { :type => "limit", :name => "business_minutes", :active => true },
  { :type => "limit", :name => "time_of_day", :active => true },
  { :type => "claim", :name => "Insured Vehicle (IV)", :active => true },
  { :type => "claim", :name => "Claimant Vehicle (CV)", :active => true },
  { :type => "location", :name => "Residence", :active => true },
  { :type => "location", :name => "Business", :active => true },
  { :type => "location", :name => "Residential Street", :active => true },
  { :type => "location", :name => "Highway", :active => true },
  { :type => "location", :name => "Impound", :active => true },
  { :type => "coverage", :name => "Comprehensive", :active => true },
  { :type => "coverage", :name => "Collision", :active => true },
  { :type => "vehicle", :name => "automobile", :active => true },
  { :type => "response", :name => "Claim Audit", :active => true },
  { :type => "metric", :name => "amount", :active => true },
  { :type => "metric", :name => "percent", :active => true },
  { :type => "metric", :name => "integer", :active => true },
  { :type => "metric", :name => "decimal", :active => true },
  { :type => "carrier_mail", :name => "billing", :active => true },
  { :type => "carrier_mail", :name => "payment", :active => true },
  { :type => "carrier_mail", :name => "dispatch", :active => true },
  { :type => "document", :name => "estimate", :active => true },
  { :type => "document", :name => "supplement", :active => true },
  { :type => "document", :name => "guidelines", :active => true },
  { :type => "document", :name => "avatar", :active => true },
  { :type => "document", :name => "logo", :active => true },
  { :type => "audit", :name => "estimate", :active => true },
  { :type => "audit", :name => "customer_service", :active => true }
])

end

if SystemAuditCategory.count == 0
SystemAuditCategory.create!([
  { :audit_type_id => 42, :name => "Administrative", :exception_name => "Administration Exception Percent", :sequence => 1, :is_exception => true, :is_impact => false, :is_estimating => false, :active => true, :timestamp => "2013-10-26 14:12:04", :last_employee_id => 0 },
  { :audit_type_id => 42, :name => "Compliance", :exception_name => "Compliance Exception Percent", :sequence => 2, :is_exception => true, :is_impact => false, :is_estimating => false, :active => true, :timestamp => "2013-10-26 14:12:04", :last_employee_id => 0 },
  { :audit_type_id => 42, :name => "Estimating", :exception_name => "Leakage Percent (Exception)", :sequence => 3, :is_exception => false, :is_impact => true, :is_estimating => true, :active => true, :timestamp => "2013-10-26 14:12:04", :last_employee_id => 0 }
])
end

if SystemAuditSubcategory.count == 0
SystemAuditSubcategory.create!([
  { :audit_category_id => 1, :name => "Estimate Complete", :sequence => 1, :minimum => 0.01, :maximum => 0.1, :active => true, :timestamp => "2013-10-27 15:52:03", :last_employee_id => 0 },
  { :audit_category_id => 1, :name => "Vehicle Complete", :sequence => 2, :minimum => 0.01, :maximum => 0.1, :active => true, :timestamp => "2013-10-27 15:52:03", :last_employee_id => 0 },
  { :audit_category_id => 1, :name => "Estimate Professionally Written", :sequence => 3, :minimum => 0.01, :maximum => 0.1, :active => true, :timestamp => "2013-10-27 15:52:03", :last_employee_id => 0 },
  { :audit_category_id => 2, :name => "Parts Guidelines", :sequence => 1, :minimum => 0.01, :maximum => 0.1, :active => true, :timestamp => "2013-10-27 15:52:03", :last_employee_id => 0 },
  { :audit_category_id => 2, :name => "State Guidelines", :sequence => 2, :minimum => 0.01, :maximum => 0.1, :active => true, :timestamp => "2013-10-27 15:52:03", :last_employee_id => 0 },
  { :audit_category_id => 2, :name => "Carrier Guidelines", :sequence => 3, :minimum => 0.01, :maximum => 0.1, :active => true, :timestamp => "2013-10-27 15:52:03", :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "Tax Rate Correct", :sequence => 1, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "Correct Tax Structure", :sequence => 2, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "Labor Rates Supported", :sequence => 3, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "Repair Decision Accurate", :sequence => 4, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "Repair Decision Accurate", :sequence => 5, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "Labor Hours Accurate", :sequence => 6, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 },
  { :audit_category_id => 3, :name => "APU Accurate", :sequence => 7, :minimum => 0.0, :maximum => 0.0, :active => true, :timestamp => nil, :last_employee_id => 0 }
])

end

if SystemEstimatingCategory.count == 0
SystemEstimatingCategory.create!([
  { :audit_type_id => 42, :name => "Estimating Time (Average)", :abbreviation => "Avg Time", :metric_type_id => 33, :sequence => 1, :active => true, :timestamp => "2013-10-26 14:11:08", :last_employee_id => 0 },
  { :audit_type_id => 42, :name => "Average Severity", :abbreviation => "Severity", :metric_type_id => 30, :sequence => 2, :active => true, :timestamp => "2013-10-26 14:11:08", :last_employee_id => 0 },
  { :audit_type_id => 42, :name => "Alternate Parts Use", :abbreviation => "APU%", :metric_type_id => 31, :sequence => 3, :active => true, :timestamp => "2013-10-26 14:11:08", :last_employee_id => 0 },
  { :audit_type_id => 42, :name => "Percent of Labor", :abbreviation => "Labor%", :metric_type_id => 31, :sequence => 4, :active => true, :timestamp => "2013-10-26 14:11:08", :last_employee_id => 0 },
  { :audit_type_id => 42, :name => "Supplement Percent", :abbreviation => "Supp%", :metric_type_id => 31, :sequence => 5, :active => true, :timestamp => "2013-10-26 14:11:08", :last_employee_id => 0 }
])

end

unless Employee.find_by_email('master@admin.com')
  Employee.create! :email => 'master@admin.com', :first_name => "Admin", :last_name => "Master", :password => "master1234", :password_confirmation => "master1234", :is_admin? => true, :role_id => 0, :timestamp => DateTime.now
end